import ProductMain from "../components/product/ProductMain";
import "./product.css";
export const metadata = {
  title: "Mattresses",
  description: "Generated by create next app",
};
const Product = () => {
  return (
    <>
      <ProductMain />
    </>
  );
};

export default Product;
